### ISSUE TITLE
Cleverbot webservicemin is down

### ISSUE THREAD

**Issue by LoveMetal-StrangeGames** [pierredavidbelanger/chatter-bot-api#15]
*C#, .NET 4.5, VS 2015*
The url http://www.cleverbot.com/webservicemin 404'd for me, so it raised an exception:

    System.Net.WebException: The remote server returned an error: (404) Not Found.
       at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at ChatterBotAPI.Utils.<Post>d__2.MoveNext()

in `Utils.Post(string url, IDictionary<string, string> parameters)`

**Comment by pierredavidbelanger** [comment]
Hi,
seeing the signature of the Utils.Post method, it seems you are not using the latest version of the lib.

This method now [takes 3 parameters](https://github.com/pierredavidbelanger/chatter-bot-api/blob/master/dotnet/ChatterBotAPI/Utils.cs#L79).

This was changed to handle cookies, which is now required (and this is why you got a 404).
