### ISSUE TITLE
org.xml.sax.SAXParseException; Premature end of file.

### ISSUE THREAD

**Issue by Kurimatzu** [pierredavidbelanger/chatter-bot-api#46]
[Fatal Error] :-1:-1: Premature end of file.
org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.google.code.chatterbotapi.Utils.xPathSearch(Utils.java:143)
	at com.google.code.chatterbotapi.Pandorabots$Session.think(Pandorabots.java:53)
	at com.google.code.chatterbotapi.Pandorabots$Session.think(Pandorabots.java:61)

**Comment by pierredavidbelanger** [comment]
From the stack trace, I can guess that [pandorabots talk XML API](http://www.pandorabots.com/pandora/talk-xml) returned an empty response.

This should not happen, except if they are down or if you have network problems. They usually respond with something (at least an error message).

I will not investigate this one, except if you can provide me a way to reproduce this at will, in this case please re open the issue.

Thank you!

**Comment by Kurimatzu** [comment]
@pierredavidbelanger I think at the time I tried to access, the PandoraBots was offline.

Now works perfectly.

**Comment by pierredavidbelanger** [comment]
Thank you for the feedback.
